### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by joaovicsoares** [silvestrinigor/Plataforma_de_Comercio_Eletronico#1]
- [ ] Estabelecer uma relação com as disciplinas que você estudou no decorrer do semestre, bem como o curso no qual você está matriculado.

- [ ] Avaliar o grau de contribuição que proporcionará para o seu desenvolvimento acadêmico e profissional. 

- [ ] Avaliar a relevância para sua formação profissional.

- [ ] Analisar as peculiaridades do case em relação aos demais.

- [ ] Analisar como você tomou conhecimento deste case? qual a fonte?

- [ ] Buscar o maior número de informações sobre o case.

- [ ] Analisar a viabilidade prática, ou seja, se é viável realizar a análise ou estudo do objeto escolhido dentro dos recursos disponíveis, incluindo tempo e acesso aos dados.
